### ISSUE TITLE
Error in docker export-server

### ISSUE THREAD

**Issue by itspheras** [CUBETIQ/highcharts-export-server-docker#2]
Error:

root@white-maned-horse-01:/home/sysadmin/docker# docker logs highcharts-export-server
    __  ___       __         __               __
   / / / (_)___ _/ /_  _____/ /_  ____ ______/ /______
  / /_/ / / __ `/ __ \/ ___/ __ \/ __ `/ ___/ __/ ___/
 / __  / / /_/ / / / / /__/ / / / /_/ / /  / /_(__  )
/_/ /_/_/\__, /_/ /_/\___/_/ /_/\__,_/_/   \__/____/
        ____//___/                  __     _____
       / ____/  ______  ____  _____/ /_   / ___/___  ______   _____  _____
      / __/ | |/_/ __ \/ __ \/ ___/ __/   \__ \/ _ \/ ___/ | / / _ \/ ___/
     / /____>  </ /_/ / /_/ / /  / /_    ___/ /  __/ /   | |/ /  __/ /
    /_____/_/|_/ .___/\____/_/   \__/   /____/\___/_/    |___/\___/_/
              /_/
                                                                     v3.0.4
Sun Aug 04 2024 09:04:51 GMT+0000 [error] - [cache] Error fetching script https://code.highcharts.com/modules/variable-pie.js: AggregateError.
Sun Aug 04 2024 09:04:51 GMT+0000 [error] - [cache] Unable to update local Highcharts cache.
Sun Aug 04 2024 09:04:56 GMT+0000 [error] - [pool] Error when acquiring worker of an event id 1: TimeoutError: operation timed out for an unknown reason
    at /usr/local/lib/node_modules/@cubetiq/highcharts-export-server/node_modules/tarn/dist/PendingOperation.js:17:27
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7)
    at async init (file:///usr/local/lib/node_modules/@cubetiq/highcharts-export-server/lib/pool.js:212:29)
    at async Object.initPool (file:///usr/local/lib/node_modules/@cubetiq/highcharts-export-server/lib/index.js:61:5)
    at async start (file:///usr/local/lib/node_modules/@cubetiq/highcharts-export-server/bin/cli.js:53:7)
Sun Aug 04 2024 09:04:56 GMT+0000 [error] - [pool] Couldn't create the worker pool Error: operation timed out for an unknown reason
Sun Aug 04 2024 09:04:56 GMT+0000 [error] - [pool] Error when creating worker of an event id 2: TimeoutError: operation timed out for an unknown reason
    at /usr/local/lib/node_modules/@cubetiq/highcharts-export-server/node_modules/tarn/dist/PendingOperation.js:17:27

**Comment by itspheras** [comment]
if i download  https://code.highcharts.com/modules/variable-pie.js in docker image then everything is fine:
root@white-maned-horse-01:/home/sysadmin/docker# docker exec  -it highcharts-export-server wget https://code.highcharts.com/modules/variable-pie.js
Connecting to code.highcharts.com (188.114.99.229:443)
saving to 'variable-pie.js'
variable-pie.js      100% |*******************************************************************************************************************************|  3604  0:00:00 ETA
'variable-pie.js' saved
